# Generated by Django 2.2.4 on 2020-04-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passageway', '0002_auto_20200415_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='importexport',
            name='status',
            field=models.IntegerField(default=0, verbose_name='状态'),
        ),
    ]
