# Generated by Django 2.2.4 on 2020-04-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passageway', '0005_auto_20200415_0648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importexport',
            name='fagentnum',
            field=models.CharField(max_length=50, null=True, verbose_name='经销商编码'),
        ),
        migrations.AlterField(
            model_name='importexport',
            name='fdatetime',
            field=models.DateTimeField(null=True, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='importexport',
            name='fitermno',
            field=models.CharField(max_length=50, null=True, verbose_name='商品编号'),
        ),
        migrations.AlterField(
            model_name='importexport',
            name='fqty',
            field=models.IntegerField(null=True, verbose_name='商品数量'),
        ),
        migrations.AlterField(
            model_name='importexport',
            name='ftoagentnum',
            field=models.CharField(max_length=50, null=True, verbose_name='去向单位'),
        ),
        migrations.AlterField(
            model_name='importexport',
            name='ftype',
            field=models.CharField(max_length=10, null=True, verbose_name='出/入'),
        ),
        migrations.AlterField(
            model_name='importexport',
            name='status',
            field=models.IntegerField(null=True, verbose_name='状态'),
        ),
    ]
